<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>VAR</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-07-25T11:24:05</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>8419e7a2-578b-4b13-9239-d5015aae8364</testSuiteGuid>
   <testCaseLink>
      <guid>6e2ebb88-bae1-4e5a-9596-89f9bb426b1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DAY2/Test VAR</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6aaf302d-9f3f-4644-9b02-d052580f9f00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a21da480-6e61-47ea-a44a-fe508a8c3afa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4440f259-56fb-4894-bd89-c98ae727fe63</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d3c668b-f8fb-449d-8948-f0c18784b025</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/DAY2/Test VAR_global</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>885d2429-0bc8-4aab-bafd-e691e86d6248</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83faa7e6-a3d2-4055-bc8b-dabee65f46a0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c9e7a44-451e-431e-a42a-4dd264f55282</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
